"""
PDF Generator for route sheets
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch
from typing import Dict
import io

def generate_route_pdf(driver_name: str, route_data: Dict, date: str) -> bytes:
    """
    Generate PDF route sheet
    
    Args:
        driver_name: Name of driver
        route_data: Route data dict with stops and summary
        date: Date string
    
    Returns:
        PDF as bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title = Paragraph(f"<b>Route Sheet - {driver_name}</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 0.2*inch))
    
    # Date and Summary
    summary = route_data.get('summary', {})
    summary_text = f"""
    <b>Date:</b> {date}<br/>
    <b>Total Stops:</b> {summary.get('total_stops', 0)}<br/>
    <b>Distance:</b> {summary.get('total_distance_miles', 0)} miles<br/>
    <b>Drive Time:</b> {summary.get('total_drive_time_min', 0)} minutes<br/>
    <b>Start:</b> {summary.get('start_time', 'TBD')} from {summary.get('start_location', 'TBD')}<br/>
    <b>Estimated Finish:</b> {summary.get('estimated_finish', 'TBD')}
    """
    elements.append(Paragraph(summary_text, styles['Normal']))
    elements.append(Spacer(1, 0.3*inch))
    
    # Stops table
    stops = route_data.get('stops', [])
    
    table_data = [['#', 'Type', 'Address', 'Items', 'ETA', 'Window']]
    
    for stop in stops:
        table_data.append([
            str(stop['stop_number']),
            stop['order_type'],
            f"{stop['address']}, {stop['city']}",
            stop['items'][:30] + '...' if len(stop['items']) > 30 else stop['items'],
            stop['eta'],
            stop['time_window']
        ])
    
    table = Table(table_data, colWidths=[0.4*inch, 0.8*inch, 2.5*inch, 1.5*inch, 0.8*inch, 1.2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Footer
    footer = Paragraph("<i>Generated by DME Route Planner | Questions? Call 760-879-1071</i>", styles['Normal'])
    elements.append(footer)
    
    # Build PDF
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
